### ISSUE TITLE
AV1 CRF mode problem (bitrate is too high)

### ISSUE THREAD

**Issue by blackmind12** [amd/ama-sdk#1]
When encoding with AV1 with CRF on and QP set, the resulting bitrate is too high. In other words, there is not much difference in bitrate whether QP is set to 1 or 51.

**Comment by AshokKumarChattala** [comment]
Hello Dear,

Could you please use either the AMD [Video forum](https://support.xilinx.com/s/topic/0TO2E000000YKY8WAO/video?language=en_US) board or please file a case with us in our [service](https://www.xilinx.com/support.html) portal?

**Comment by NastoohX** [comment]
Thank you for bringing this issue to our attention. When CRF mode is enabled, QP value controls the target quality and takes on its allowable range, i.e., 0-51 for AVC and HEVC, and 0-255 for AV1. (See https://amd.github.io/ama-sdk/v1.0/examples/ffmpeg/tutorials.html#constant-rate-factor-crf-mode) Let us know if this wider range provides the desired outcome.
Cheers,

**Comment by NastoohAMD** [comment]
Issue moved to Xilinx Video forum, for further investigation. Please refer to the following link for future discussions: https://support.xilinx.com/s/question/0D54U000088Q93SSAS/av1-crf-mode-problem-bitrate-is-too-high-from-amsdk-github
