### ISSUE TITLE
Bug: v1.1 XRM interface SDK contains ABI break in `XrmInterfaceProperties`

### ISSUE THREAD

**Issue by tt2468** [amd/ama-sdk#10]
With the v1.1 API, the `XrmInterfaceProperties` struct changed size, which breaks ABI. This causes the SDK implementation to over-read memory on applications built against the 1.0 API headers.

The most common way this shows up is `xrm_enc_reserve()` returning a fail response, and `[ERROR] AMA.XRM:{2403} Found unsupported enc_cores(0)` being logged to console.

The XRM API appears to function correctly outside of this ABI break.

**Comment by tt2468** [comment]
An application compiled against 1.0 will error out or crash when run against v1.1 or v1.1.1

**Comment by NastoohAMD** [comment]
Thank you for the extra info. I have opened an internal ticket and will provide updates, when available.
Internal Ticket: CR-1191579
Cheers,

**Comment by NastoohAMD** [comment]
Hi,
After further investigation, we have confirmed that there was a regression in 1.1.1 SDK and your observation wrt ABI incompatibility is correct. The issue has been rectified in our upcoming next release and 1.1.1 documentation has been updated to note the above.
Thank you again for finding and reporting this issue.
Cheers,

**Comment by NastoohAMD** [comment]
Closing this thread, as no further action is required.
