### ISSUE TITLE
Feature Request: V4L2-M2M support

### ISSUE THREAD

**Issue by Ambyjkl** [amd/ama-sdk#11]
It would be great to have V4L2-M2M support, especially for decoding, so that applications that implement V4L2 decoding can be easily accelerated.

**Comment by Ambyjkl** [comment]
I'm considering running applications like Firefox and Chromium. Firefox already implements v4l2-m2m (https://bugzilla.mozilla.org/show_bug.cgi?id=1833354), and Chromium has a WIP implementation.

**Comment by NastoohAMD** [comment]
Closing this item, as it is tracked offline.
