### ISSUE TITLE
mautil examine output goes to stderr instead of stdout

### ISSUE THREAD

**Issue by screavalle** [amd/ama-sdk#12]
When running mautil examine, the output is going to stderr. 
<img width="613" alt="image" src="https://github.com/amd/ama-sdk/assets/96153630/ef8626cf-6f7a-41bd-a180-999a86cdf75a">
This does not occur for mautil validate

**Comment by NastoohAMD** [comment]
Thank you for your feedback. Kindly, file the issue at: https://support.xilinx.com/s/?language=en_US.
Cheers,
