### ISSUE TITLE
Download link for ma35d SDK 1.2 results in 404

### ISSUE THREAD

**Issue by ErikWAberg** [amd/ama-sdk#13]
The download link to SDK 1.2, as referenced on page: https://amd.github.io/ama-sdk/latest/git_hub.html, refers to 'https://github.com/amd/ama-sdk/blob/v1.2/', which results in a 404.

```
<p>AMD AMA Video SDK ... located at <a ... href="https://github.com/amd/ama-sdk/blob/v1.2/">ma35d sdk v1.2</a></p>
```

**Comment by NastoohAMD** [comment]
Hi,
Thank you for bringing this issue to our attention. Please refresh your browser and try the link again.
As "issues" link is not monitored regularly, kindly, proceed with support requests through https://www.xilinx.com/support.html link.
Cheers,
