### ISSUE TITLE
Setting values when CRF mode is on (av1)

### ISSUE THREAD

**Issue by blackmind12** [amd/ama-sdk#2]
Hello,

I have a few questions.

Is it not possible to set the max_bitrate when using CRF mode with the AV1 codec?
Is it correct that there is no 'qp' in Dynamic Encoder Parameters? If so, are there plans to add it in the future?

thank you.

**Comment by AshokKumarChattala** [comment]
Hello Dear,

Could you please use either the AMD [Video forum](https://support.xilinx.com/s/topic/0TO2E000000YKY8WAO/video?language=en_US) board or please file a case with us in our [service](https://www.xilinx.com/support.html) portal?

**Comment by NastoohX** [comment]
Thank you for bringing this issue to our attention. As of now, capped CRF is not a supported mode; however, similar behaviour can be obtained by using either CBR or CVBR modes. With respect to dynamic qp, similar outcome can be obtained by setting both max_qp and min_qp to the target qp value.
Cheers,

**Comment by NastoohAMD** [comment]
Issue moved to Xilinx Video forum, for further investigation. Please refer to the following link for future discussions: https://support.xilinx.com/s/question/0D54U000088QAbhSAG/setting-values-when-crf-mode-is-on-av1-from-amasdk-github-httpsgithubcomamdamasdkissues2
