### ISSUE TITLE
Bug: setup.sh script specifies invalid LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by tt2468** [amd/ama-sdk#3]
The setup.sh file included with SDK 1.0.0 includes the following line:

`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/amdgpu-pro/lib/x86_64-linux-gnu/`

This appears to be a mistake, a valid path would be `/opt/amd/ama/ma35/lib`. As of right now, I have to export the correct path manually for my program using the SDK to load the module correctly.

**Comment by durgabhavaniv** [comment]
Hi @tt2468,

Could you please use either the AMD [Video forum](https://support.xilinx.com/s/topic/0TO2E000000YKY8WAO/video?language=en_US) board or please file a case with us in our [service](https://www.xilinx.com/support.html) portal?

Regards,
Durga.

**Comment by NastoohX** [comment]
Thank you for bringing this issue to our attention. It is now internally tracked via ticket number:  CR-1189457
Cheers,

**Comment by tt2468** [comment]
> Hi @tt2468,
> 
> Could you please use either the AMD [Video forum](https://support.xilinx.com/s/topic/0TO2E000000YKY8WAO/video?language=en_US) board or please file a case with us in our [service](https://www.xilinx.com/support.html) portal?
> 
> Regards, Durga.

Your documentation site links to here to file an issue: https://i.imgur.com/T6Ni5cW.png

So which one is it?

**Comment by NastoohX** [comment]
Hi,
Both are applicable depending on the the type of issue raised. Kindly, proceed as advised.
Cheers,

**Comment by tt2468** [comment]
Given that there's an internal ticket opened, is there a place I should go to check the status of it or will updates be shared in this issue?

Thanks

**Comment by NastoohX** [comment]
Hi,
Indeed, updates will be shared here.
Cheers,

**Comment by tt2468** [comment]
I have a binary which links to xma and xrm_interface, and `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/amd/ama/ma35/lib` is necessary in order for the application to load the libraries on startup. Could this be added to the setup.sh file?

**Comment by DSupuran** [comment]
It's not a best practice for setup.sh to globally modify and influence the LD paths.

a few options you could do:
- Modify your build process for your binary and utilize the linker flag `-rpath` to embed the /opt/amd/ama/ma35/lib path so your binary will check it before it checks LD_LIBRARY_PATH.
- Create a wrapper script to change the environment variable LD_LIBRARY_PATH and then run your binary, so it only affects that application and not others.
- Create symlinks in standard paths to the ma35/lib shared libraries for your local installations
- Modify /etc/ld.so.conf.d/ and force /opt/amd/ama/ma35/lib to be loaded with ldconfig's path cache always on that server.
- Staticly compile the library into your binary

These are all viable options and have pros and cons, however for AMD to modify it for everyone who installs their SDK, then it could have a negative impact on running applications as it could change the shared libraries that are utilized for pre-existing applications at the server scope.  This could break servers if done wrong, so I'm sure this has some consideration why they did not do it as a default.  I have a one time setup script per MA35D server I run to customize it 'how I want it'.
