### ISSUE TITLE
Bug (?): Opening encoder using `props.sw_format = XMA_NV12_FMT_TYPE` fails

### ISSUE THREAD

**Issue by tt2468** [amd/ama-sdk#4]
Attempting to open an encoder with `props.sw_format = XMA_NV12_FMT_TYPE` and `props.format = XMA_VPE_FMT_TYPE` logs an exception: `InternalEncoderSession::StartEncoder() Unable to open encoder for processing!`

In syslog, another, two more descriptive errors are logged:
```
[ERROR] AMA.SDK.ENC.encoder_@0x56074247a110:{13021} Only NV12 Tile format supported
[ERROR] AMA.VPI.ENC.encoder_@0x56074247a110:{13021} vpe_encoder_xav1_open failed#012
```

**Comment by tt2468** [comment]
Seems to be an internal format, like the other formats in the enum. Only I420 seems to be working correctly when DMA'ing frames to the card.

**Comment by durgabhavaniv** [comment]
Hi @tt2468,

Could you please use either the AMD [Video forum](https://support.xilinx.com/s/topic/0TO2E000000YKY8WAO/video?language=en_US) board or please file a case with us in our [service](https://www.xilinx.com/support.html) portal?

Regards,
Durga.

**Comment by NastoohX** [comment]
Thank you for bringing this issue to our attention. It is now internally tracked via ticket number:  CR-1189456
Cheers,

**Comment by NastoohAMD** [comment]
Hi,
Online documentation has been updated to reflect format restriction. Please see https://amd.github.io/ama-sdk/v1.0/c_apis.html#:~:text=Note-,Xma,-%5BScaler%7CEncoder%7CFilter.
Cheers,

**Comment by tt2468** [comment]
Thanks!
