### ISSUE TITLE
Feature Request: DMA of frames with stride sizes not aligned to 256

### ISSUE THREAD

**Issue by tt2468** [amd/ama-sdk#5]
It seems that the MA35D requires plane stride lengths that are aligned 256 bytes (stride of 1920 requires padding to 2048 before DMA). Many existing applications output frames which are not padded in this way, requiring a new video frame to be allocated to the aligned amount, then copying of the data to that destination.

If it's possible to support non-aligned DMA, to avoid that copy, then performance of DMA would be significantly improved.

**Comment by durgabhavaniv** [comment]
Hi @tt2468,

Could you please use either the AMD [Video forum](https://support.xilinx.com/s/topic/0TO2E000000YKY8WAO/video?language=en_US) board or please file a case with us in our [service](https://www.xilinx.com/support.html) portal?

Regards,
Durga.

**Comment by NastoohAMD** [comment]
Hi,
This issue is resolved in the upcoming  1.1.2 release.
Cheers,

**Comment by tt2468** [comment]
Curious how this was resolved? I understand that there is probably a hardware limitation for the aligned DMA. Right now we're avoiding a copy stage by writing to an already-aligned host frame. Is the fix implemented as just another host frame copy internally, or is it actually able to accept non-aligned buffers without an additional full copy?

**Comment by NastoohAMD** [comment]
Issue moved to Xilinx Video forum, for further investigation. Please refer to the following link for future discussions: https://support.xilinx.com/s/question/0D54U000088QBBySAO/feature-request-dma-of-frames-with-stride-sizes-not-aligned-to-256-from-amasdk-github-httpsgithubcomamdamasdkissues5
