### ISSUE TITLE
xrmd service binds to all interfaces/IPs

### ISSUE THREAD

**Issue by DSupuran** [amd/ama-sdk#7]
I wanted to confirm if this is a defect or intentional by design.

**Concern:**
While doing a security audit it was noticed that the Xilinx Resource Manger Daemon (xrmd) was binding to every IP address on TCPv4 port 9763 with no authentication or encryption. Some servers that use the AMD MA35D accelerator cards will have public exposed IP addresses.  This means that any anonymous actor on the internet can interface with the xrmd service that is running as root which increases the risk footprint from a security perspective.

COMMAND  PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
xrmd    1957 root    7u  IPv4  22942      0t0  TCP *:9763 (LISTEN)

**Referenced from:**
_https://www.xilinx.com/content/dam/xilinx/guest-resources/2023/video/ma35d_sdk_v1.0_xrm.zip
src/daemon/xrm_tcp_server.hpp:_
![image](https://github.com/amd/ama-sdk/assets/651175/ed613885-2529-461e-852b-92f7aa76ebe1)

**Current Workaround (for end users):**
Ensure a firewall is restricting TCPv4 incoming connects to port 9763 for interfaces and/or public IP addresses not intended to communicate with xrmd based on use cases.

**Suggestion:**
Bind to localhost only, localhost and non routable private IPs (ex. 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16), provide a configuration method to choose interfaces/IPs to bind to, and/or provide an authentication mechanism to restrict access such as mTLS, JWT, password, etc.

**Comment by tt2468** [comment]
As a user implementing the SDK right now, this is an unnerving find. Seems like a serious DoS risk. Given the linux-only support for the SDK, it would seem that using UNIX domain sockets would be the best case.

**Comment by durgabhavaniv** [comment]
Hi all,

Could you please use either the AMD [Video forum](https://support.xilinx.com/s/topic/0TO2E000000YKY8WAO/video?language=en_US) board or please file a case with us in our [service](https://www.xilinx.com/support.html) portal?

Regards,
Durga.

**Comment by NastoohX** [comment]
Thank you for bringing this issue to our attention. It is now internally tracked via ticket number:  CR-1189353
Cheers,

**Comment by DSupuran** [comment]
> I am also having this issue. I cannot open any forum topics because of the salesforce error above.

I eventually contacted account.help@amd.com who were able to internally contact the SSO support team about a day later and they fixed my account today.  Give this a try and see if it helps you.

**Comment by NastoohX** [comment]
Hi,
Thank you for bringing this issue to our attention. I have asked our support group to look into this and will provide updates/instructions as soon as they are available.
Cheers,

**Comment by NastoohX** [comment]
> > I am also having this issue. I cannot open any forum topics because of the salesforce error above.
> 
> I eventually contacted [account.help@amd.com](mailto:account.help@amd.com) who were able to internally contact the SSO support team about a day later and they fixed my account today. Give this a try and see if it helps you.

Thank you for sharing your solution.
Cheers,

**Comment by NastoohX** [comment]
Hi,
Seems that this is a known issue. Prior to contacting the helpline, as noted by @DSupuran, try clearing your browser's cache or start a new session.
Let us know if this helps.
Cheers,

**Comment by tt2468** [comment]
Clearing browser cache does not work for me, neither does trying it in an incognito tab. Seems like a forum issue to me.

**Comment by NastoohAMD** [comment]
Issue moved to Xilinx Video forum, for further investigation. Please refer to the following link for future discussions: https://support.xilinx.com/s/question/0D54U000088QEXySAO/xrmd-service-binds-to-all-interfacesips-from-amasdk-github-httpsgithubcomamdamasdkissues7
