### ISSUE TITLE
How were the performance tables calculated?

### ISSUE THREAD

**Issue by knpwrs** [amd/ama-sdk#8]
At https://amd.github.io/ama-sdk/v1.0/specs_and_features.html#id8 I see the following table:

<img width="710" alt="image" src="https://github.com/amd/ama-sdk/assets/174864/db42d45f-2d5f-4e3b-a2e9-de45973d6238">

According to that, I should be able to take up to four 4k source videos and transcode them to multiple bitrate output files. However, I seem to only be able to do three ffmpeg transcode jobs simultaneously. The fourth jobs fails as such:

```
[Parsed_scaler_ama_0 @ 0x563a532d8140] Enabling pipeline in XABR
SCALER cu_load 240277
Num CU pools available 1
Type 2, ENCODER cu load 400000, LOOKAHEAD load 200000
Insufficient resources available for allocation
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!
```

When I set `-lookahead_depth` to `0`, I get the same failure. I've also seen this:

```
[Parsed_scaler_ama_0 @ 0x55bb686b3a00] Enabling pipeline in XABR
SCALER cu_load 240277
Num CU pools available 2
Type 2, ENCODER cu load 400000, LOOKAHEAD load 200000
Insufficient resources available for allocation
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!
```

This is with `-preset medium` and `-tune_metrics` as well (options I tried adding after noticing the failure after three jobs).

**Comment by durgabhavaniv** [comment]
Hi @knpwrs 

Could you please use either the AMD [Video forum](https://support.xilinx.com/s/topic/0TO2E000000YKY8WAO/video?language=en_US) board or please file a case with us in our [service](https://www.xilinx.com/support.html) portal?

Regards,
Durga.

**Comment by knpwrs** [comment]
Sure thing. I opened a thread here: https://support.xilinx.com/s/question/0D54U000081GRI5SAO/i-can-only-get-the-ma35d-to-simultaneously-transcode-three-videos-at-a-time-how-were-the-performance-tables-generated?language=en_US

Thank you!
